controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api:
    resource: '../src/Controller/Api/'
    type: annotation
    prefix: /api

api_login_check:
    path: /login
    methods: [POST]
